
services:
  mysqldb:
    image: mysql:8.0
    container_name: mysqldb
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: root
    ports:
      - 3307:3306
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - spring-boot-network
    restart: unless-stopped

  eurekaserver:
    image: darkmayor/eurekaserver
    container_name: eurekaserver
    ports:
      - 8761:8761
    depends_on:
      - rabbitmq
      - zipkin
      - mysqldb
    networks:
      - spring-boot-network

  companyservice:
    image: darkmayor/companyservice
    container_name: companyservice
    ports:
      - 8082:8082
    depends_on:
      - eurekaserver
    networks:
      - spring-boot-network
      - mysql
    environment:
      - SPRING_PROFILES_ACTIVE=docker

  jobservice:
    image: darkmayor/jobservice
    container_name: jobservice
    ports:
      - 8081:8081
    depends_on:
      - eurekaserver
    networks:
      - spring-boot-network
      - mysql
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eurekaserver:8761/eureka

  reviewservice:
    image: darkmayor/reviewservice
    container_name: reviewservice
    ports:
      - 8083:8083
    depends_on:
      - eurekaserver
    networks:
      - spring-boot-network
      - mysql
    environment:
      - SPRING_PROFILES_ACTIVE=docker

  gateway:
    image: darkmayor/apigateway
    ports:
      - 8084:8084
    depends_on:
      - eurekaserver
    networks:
      - spring-boot-network
    environment:
      - SPRING_PROFILES_ACTIVE=docker

  zipkin:
    image: openzipkin/zipkin
    container_name: zipkin
    ports:
      - 9411:9411
    networks:
      - spring-boot-network

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
    networks:
      - spring-boot-network

networks:
  spring-boot-network:
    driver: bridge
  mysql:
    driver: bridge

volumes:
  mysql_data:



#services:
#  companyservice:
#    image: openjdk:17-jdk-slim
#    container_name: companyservice
#    ports:
#      - 8082:8082
#    environment:
#      SPRING_DATASOURCE_URL: jdbc:mysql://job_service_db:3306/companyservice
#      SPRING_DATASOURCE_USERNAME: root
#      SPRING_DATASOURCE_PASSWORD: root
#    volumes:
#      - ./target/CompanyService-0.0.1-SNAPSHOT.jar:/app/CompanyService-0.0.1-SNAPSHOT.jar
#    command: "java -jar /app/CompanyService-0.0.1-SNAPSHOT.jar"
#    networks:
#      - spring-boot-network
#    restart: unless-stopped
#    depends_on:
#      - job_service_db


#  job_service_db:
#    image: mysql:8.0
#    container_name: job_service_db
#    ports:
#      - 3307:3306
#    environment:
#      MYSQL_DATABASE: companyservice
#      MYSQL_ROOT_PASSWORD: root
#    networks:
#      - spring-boot-network
#    restart: unless-stopped
#    volumes:
#      - db_data:/var/lib/mysql
#
#  rabbitMQ:
#    image: rabbitmq:3-management
#    container_name: rabbitmq
#    ports:
#      - 5672:5672
#      - 15672:15672
#    networks:
#      - spring-boot-network
#
#  zipkin:
#    container_name: zipkin
#    image: openzipkin/zipkin
#    ports:
#      - 9411:9411
#    networks:
#      - spring-boot-network



#new configs
#services:
#  mysql_db:
#    image: mysql:8.0
#    container_name: mysql
#    environment:
#      MYSQL_ROOT_PASSWORD: root
#      MYSQL_DATABASE: root
#      MYSQL_USER: root
#      MYSQL_PASSWORD: root
#    ports:
#      - 3306:3306  # Map port 3306 in the container to port 3306 on the host
#    volumes:
#      - mysql_data:/var/lib/mysql
#    networks:
#      - spring-boot-network
#    restart: unless-stopped
#
#  eurekaserver:
#    image: darkmayor/eurekaserver
#    container_name: eurekaserver
#    ports:
#      - 8761:8761
#    depends_on:
#      - rabbitmq
#      - zipkin
#      - mysql_db
#    networks:
#      - spring-boot-network
#
#  companyservice:
#    image: darkmayor/companyservice
#    container_name: companyservice
#    ports:
#      - 8082:8082
#    depends_on:
#      - eurekaserver
#    networks:
#      - spring-boot-network
#      - mysql
#    environment:
#      - SPRING_PROFILES_ACTIVE=docker
#  jobservice:
#    image: darkmayor/jobservice
#    container_name: jobservice
#    ports:
#      - 8082:8082
#    depends_on:
#      - eurekaserver
#    networks:
#      - microservice-network
#      - mysql
#    environment:
#      - SPRING_PROFILES_ACTIVE=docker
#      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eurekaserver:8761/eureka
#  reviewservice:
#    image: darkmayor/reviewservice
#    container_name: reviewservice
#    ports:
#      - 8083:8083
#    depends_on:
#      - eurekaserver
#    networks:
#      - spring-boot-network
#      - mysql
#    environment:
#      - SPRING_PROFILES_ACTIVE=docker
#  gateway:
#    image: darkmayor/apigateway
#    ports:
#      - 8084:8084
#    depends_on:
#      - eurekaserver
#    networks:
#      - spring-boot-network
#    environment:
#      - SPRING_PROFILES_ACTIVE=docker
#  zipkin:
#    image: openzipkin/zipkin
#    container_name: zipkin
#    ports:
#      - 9411:9411
#    networks:
#      - spring-boot-network
#      - mysql
#  rabbitmq:
#    image: rabbitmq:3-management
#    container_name: rabbitmq
#    ports:
#      - 5672:5672
#      - 15672:15672
#    networks:
#      - spring-boot-network
#      - mysql
#  networks:
#  spring-boot-network:
#    driver: bridge
#  mysql:
#    driver: bridge
#
#  volume:
#   mysql_data
